name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
    - name: ssh proxy command
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.PRIVATE_HOST }}
      username: ${{ secrets.PRIVATE_USER }}
      key: ${{ secrets.PRIVATE_KEY }}
      port: ${{ secrets.PRIVATE_PORT }}
+     proxy_host: ${{ secrets.PROXY_HOST }}
+     proxy_username: ${{ secrets.PROXY_USER }}
+     proxy_key: ${{ secrets.PROXY_KEY }}
+     proxy_port: ${{ secrets.PROXY_PORT }}
      script: |
        mkdir abc/def
        ls -al
