name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRIVATE_HOST }}
        username: ${{ secrets.PRIVATE_USER }}
        password: ${{ secrets.PRIVATE_KEYS }}
        port: ${{ secrets.PRIVATE_PORT }}
        script: whoami
                cd /home/ubuntu
                git clone https://github.com/liqteq/vidan-fe.git
